"""delete created_at

Revision ID: 483b7b0f6775
Revises: 84a3be51fed5
Create Date: 2023-07-14 14:45:01.782537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '483b7b0f6775'
down_revision = '84a3be51fed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('created_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
