"""update created_at to nullable False

Revision ID: 84a3be51fed5
Revises: b76e15dc858a
Create Date: 2023-07-14 14:42:38.370455

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '84a3be51fed5'
down_revision = 'b76e15dc858a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
