"""update created_at to nullable False

Revision ID: b76e15dc858a
Revises: 5535f2dc2973
Create Date: 2023-07-14 14:40:48.394692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b76e15dc858a'
down_revision = '5535f2dc2973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
